#!/bin/bash
# Usage: ./setup-refs.sh [game_directory]
# Example: ./setup-refs.sh "/mnt/c/SteamLibrary/steamapps/common/Schedule I"
#
# If game_directory is omitted, uses SCHEDULE_I_DIR environment variable
# Set in ~/.bashrc: export SCHEDULE_I_DIR="/path/to/Schedule I"
#
# IMPORTANT:
# - For Mono assemblies, switch to beta "alternate" branch in Steam first
# - Run this script twice if you want both Mono and IL2CPP assemblies

set -e

GAME_DIR="${1:-$SCHEDULE_I_DIR}"

if [ -z "$GAME_DIR" ]; then
    echo "Error: No game directory specified"
    echo "Usage: $0 [game_directory]"
    echo "Example: $0 \"/mnt/c/SteamLibrary/steamapps/common/Schedule I\""
    echo ""
    echo "Or set SCHEDULE_I_DIR environment variable:"
    echo "  export SCHEDULE_I_DIR=\"/path/to/Schedule I\""
    exit 1
fi

if [ ! -d "$GAME_DIR" ]; then
    echo "Error: Game directory not found: $GAME_DIR"
    exit 1
fi

echo "Setting up references from: $GAME_DIR"

# Create lib directories
mkdir -p libs/mono libs/il2cpp

# Verify MelonLoader installation
if [ ! -d "$GAME_DIR/MelonLoader" ]; then
    echo "Error: MelonLoader not found. Install MelonLoader and run the game once first."
    exit 1
fi

echo ""
echo "=== Copying IL2CPP assemblies ==="

# Copy IL2CPP MelonLoader.dll (net6)
if [ -f "$GAME_DIR/MelonLoader/net6/MelonLoader.dll" ]; then
    echo "  ✓ MelonLoader.dll (net6)"
    cp "$GAME_DIR/MelonLoader/net6/MelonLoader.dll" libs/il2cpp/
else
    echo "  ✗ MelonLoader.dll (net6) not found"
fi

# Copy 0Harmony.dll (net6)
if [ -f "$GAME_DIR/MelonLoader/net6/0Harmony.dll" ]; then
    echo "  ✓ 0Harmony.dll (net6)"
    cp "$GAME_DIR/MelonLoader/net6/0Harmony.dll" libs/il2cpp/
else
    echo "  ✗ 0Harmony.dll (net6) not found"
fi

# Copy IL2CPP Interop DLLs (CRITICAL - these are in net6/, not Il2CppAssemblies/)
if [ -f "$GAME_DIR/MelonLoader/net6/Il2CppInterop.Runtime.dll" ]; then
    echo "  ✓ Il2CppInterop.Runtime.dll"
    cp "$GAME_DIR/MelonLoader/net6/Il2CppInterop.Runtime.dll" libs/il2cpp/
else
    echo "  ✗ Il2CppInterop.Runtime.dll not found"
fi

if [ -f "$GAME_DIR/MelonLoader/net6/Il2CppInterop.Common.dll" ]; then
    echo "  ✓ Il2CppInterop.Common.dll"
    cp "$GAME_DIR/MelonLoader/net6/Il2CppInterop.Common.dll" libs/il2cpp/
else
    echo "  ✗ Il2CppInterop.Common.dll not found"
fi

if [ -f "$GAME_DIR/MelonLoader/net6/Il2CppInterop.HarmonySupport.dll" ]; then
    echo "  ✓ Il2CppInterop.HarmonySupport.dll (optional)"
    cp "$GAME_DIR/MelonLoader/net6/Il2CppInterop.HarmonySupport.dll" libs/il2cpp/
fi

# Copy IL2CPP unhollowed assemblies (auto-generated by MelonLoader)
if [ -d "$GAME_DIR/MelonLoader/Il2CppAssemblies" ]; then
    echo "  ✓ Assembly-CSharp.dll (unhollowed)"
    cp "$GAME_DIR/MelonLoader/Il2CppAssemblies/Assembly-CSharp.dll" libs/il2cpp/

    echo "  ✓ UnityEngine.CoreModule.dll (unhollowed)"
    cp "$GAME_DIR/MelonLoader/Il2CppAssemblies/UnityEngine.CoreModule.dll" libs/il2cpp/

    # Copy IL2CPP system assemblies (required for Il2CppSystem types)
    echo "  ✓ Il2Cppmscorlib.dll"
    cp "$GAME_DIR/MelonLoader/Il2CppAssemblies/Il2Cppmscorlib.dll" libs/il2cpp/

    echo "  ✓ Il2CppSystem.dll"
    cp "$GAME_DIR/MelonLoader/Il2CppAssemblies/Il2CppSystem.dll" libs/il2cpp/

    # Copy other Unity modules if needed (optional)
    # cp "$GAME_DIR/MelonLoader/Il2CppAssemblies/UnityEngine.UI.dll" libs/il2cpp/ 2>/dev/null || true
else
    echo "  ✗ Il2CppAssemblies directory not found"
    echo "     Run the game once to generate unhollowed assemblies"
fi

echo ""
echo "=== Copying Mono assemblies ==="

# Copy Mono MelonLoader.dll (net35)
if [ -f "$GAME_DIR/MelonLoader/net35/MelonLoader.dll" ]; then
    echo "  ✓ MelonLoader.dll (net35)"
    cp "$GAME_DIR/MelonLoader/net35/MelonLoader.dll" libs/mono/
else
    echo "  ✗ MelonLoader.dll (net35) not found"
fi

# Copy 0Harmony.dll (net35)
if [ -f "$GAME_DIR/MelonLoader/net35/0Harmony.dll" ]; then
    echo "  ✓ 0Harmony.dll (net35)"
    cp "$GAME_DIR/MelonLoader/net35/0Harmony.dll" libs/mono/
else
    echo "  ✗ 0Harmony.dll (net35) not found"
fi

# Copy Mono assemblies (beta "alternate" branch only)
if [ -d "$GAME_DIR/Schedule I_Data/Managed" ]; then
    echo "  ✓ Assembly-CSharp.dll (Mono)"
    cp "$GAME_DIR/Schedule I_Data/Managed/Assembly-CSharp.dll" libs/mono/

    echo "  ✓ UnityEngine.CoreModule.dll (Mono)"
    cp "$GAME_DIR/Schedule I_Data/Managed/UnityEngine.CoreModule.dll" libs/mono/

    # Copy other Unity assemblies if needed (optional)
    # cp "$GAME_DIR/Schedule I_Data/Managed/UnityEngine.UI.dll" libs/mono/ 2>/dev/null || true
else
    echo "  ✗ Managed directory not found"
    echo "     This is normal for IL2CPP builds"
    echo "     To get Mono assemblies:"
    echo "       1. Switch to beta 'alternate' branch in Steam"
    echo "       2. Run the game once"
    echo "       3. Re-run this script"
fi

echo ""
echo "=== Reference setup complete ==="
echo ""

# Verify critical files
MISSING=0

if [ ! -f "libs/il2cpp/MelonLoader.dll" ]; then
    echo "⚠ Missing: libs/il2cpp/MelonLoader.dll"
    MISSING=1
fi

if [ ! -f "libs/il2cpp/Il2CppInterop.Runtime.dll" ]; then
    echo "⚠ Missing: libs/il2cpp/Il2CppInterop.Runtime.dll"
    MISSING=1
fi

if [ ! -f "libs/il2cpp/Assembly-CSharp.dll" ]; then
    echo "⚠ Missing: libs/il2cpp/Assembly-CSharp.dll"
    MISSING=1
fi

if [ $MISSING -eq 1 ]; then
    echo ""
    echo "Some required files are missing. IL2CPP builds may fail."
    exit 1
fi

echo "All required IL2CPP assemblies present ✓"

if [ ! -f "libs/mono/MelonLoader.dll" ] || [ ! -f "libs/mono/Assembly-CSharp.dll" ]; then
    echo ""
    echo "Note: Mono assemblies not found. Mono builds will fail."
    echo "      This is expected if you haven't switched to the beta branch."
fi
